/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as openzeppelin from "./openzeppelin";
import type * as proxy from "./proxy";

export type { openzeppelin };

export type { proxy };
